version: '3.0'

services:
  db:
    container_name: pg01
    env_file: .env
    build:
      context: .
      dockerfile: build/db/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    networks:
      - golangnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  migrate:
    image: migrate/migrate
    container_name: mg01
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "${POSTGRES_URL}" , "up"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - golangnetwork

  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    container_name: go01
    restart: unless-stopped
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
      - migrate
    networks:
      - golangnetwork

volumes:
  local_postgres_data: {}

networks:
  golangnetwork:
