ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_payee;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_payer;

ALTER TABLE orders
ADD CONSTRAINT fk_payee FOREIGN KEY (payee) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE orders
ADD CONSTRAINT fk_payer FOREIGN KEY (payer) REFERENCES users(id) ON DELETE CASCADE;
