name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PORT: ${{ secrets.PORT }}
  GIN_MODE: ${{ secrets.GIN_MODE }}
  LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
  LOG_OUTPUT: ${{ secrets.LOG_OUTPUT }}
  AUTHORIZATION_URL: ${{ secrets.AUTHORIZATION_URL }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./internal/...
  
  check:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: make build-ci

    - name: Run E2E Tests
      run: make build-e2e-test

    - name: Tear Down
      if: always()
      run: make build-down
